server:
  port: 8086

spring:
  application:
    name: amy-server-admin
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==

jwt:
  client-header: XPLATFORM
  header: Authorization
  token-start-with: Bearer
  online-key: "app_online_token:"
  resource-permission-key: "resources_permission:"

swagger:
  title: AMY ADMIN
  description: AMY 后台接口文档
  version: v1.0.0
  contact:
    name: ashen
    url: https://github.com/ashenfuamy
    email: ayuanshen。liu@gmail.com

video-task-mq:
  exchange-name: transcoding_video-exchange
  queue-name: transcoding_video-queue
  routing-key: TRANSCODING_VIDEO:ROUTING

file:
  avatar-resource-prefix: /resource/avatar
  image-ext: .webp
  poster-resource-prefix: /resource/poster
  video-resource-prefix: /resource/video
  upload-cache-key: 'upload-file:'
  publish-resource-prefix: /resource/public